In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
sw = set(stopwords.words('english'))

from nltk.stem.wordnet import WordNetLemmatizer
wl = WordNetLemmatizer()

In [13]:
df = pd.read_csv('PC_Games_2021.csv')

In [14]:
df.head()

Unnamed: 0                         Title  \
0           0  Disco Elysium: The Final Cut   
1           1                   Half-Life 2   
2           2            Grand Theft Auto V   
3           3                The Orange Box   
4           4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0    4500 non-null   int64 
 1   Title         4500 non-null   object
 2   Description   4468 non-null   object
 3   Release Date  4500 non-null   object
 4   Metascore     4500 non-null   int64 
 5   User Score    4500 non-null   object
dtypes: int64(2), object(4)
memory usage: 211.1+ KB


In [16]:
df.reset_index(inplace=True)

In [17]:
df.head()

index  Unnamed: 0                         Title  \
0      0           0  Disco Elysium: The Final Cut   
1      1           1                   Half-Life 2   
2      2           2            Grand Theft Auto V   
3      3           3                The Orange Box   
4      4           4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [18]:
df.drop(columns=['index','Unnamed: 0'],inplace=True)

In [19]:
df.head()

Title  \
0  Disco Elysium: The Final Cut   
1                   Half-Life 2   
2            Grand Theft Auto V   
3                The Orange Box   
4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [20]:
df.dropna(inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4468 entries, 0 to 4499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Title         4468 non-null   object
 1   Description   4468 non-null   object
 2   Release Date  4468 non-null   object
 3   Metascore     4468 non-null   int64 
 4   User Score    4468 non-null   object
dtypes: int64(1), object(4)
memory usage: 209.4+ KB


In [22]:
complete_data = df.copy()
complete_data

Title  \
0     Disco Elysium: The Final Cut   
1                      Half-Life 2   
2               Grand Theft Auto V   
3                   The Orange Box   
4                        Half-Life   
...                            ...   
4495                    Rugby 2004   
4496   Judge Dredd: Dredd VS Death   
4497             Conflict: Vietnam   
4498        Transformers: The Game   
4499                  Alias (2004)   

                                            Description       Release Date  \
0     Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1     [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2     Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3     Games included in The Orange Box compilation: ...   October 10, 2007   
4     Half-Life combines great storytelling in the t...  November 19, 1998   
...                                                 ...                ...   
4495  Choose from 20 international, all Super 12, an...   November 4, 2003   
4496  It is the third decade of the 22nd century. Un...      March 3, 2005   
4497  Conflict: Vietnam follows the progress of four...    October 5, 2004   
4498  Based on the 2007 live-action feature film, Tr...      June 26, 2007   
4499  Alias is a third-person action adventure conta...      June 17, 2004   

      Metascore User Score  
0            97        8.2  
1            96        9.2  
2            96        7.8  
3            96        9.3  
4            96        9.1  
...         ...        ...  
4495         55        5.5  
4496         55        7.1  
4497         55        7.1  
4498         55        5.5  
4499         55        6.9  

[4468 rows x 5 columns]

In [39]:
new_desc = []
for desc in complete_data['Description']:
    update = re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", desc)
    update = update.split()
    update = [wl.lemmatize(word) for word in update if word.lower() not in sw]
    new_desc.append(update)

In [42]:
complete_data['Summary'] = new_desc

In [43]:
complete_data['Summary'] = complete_data['Summary'].str.join(" ")

In [44]:
complete_data['Summary'] = complete_data['Title']+ " " +complete_data['Summary']

In [45]:
complete_data.head()

index                         Title  \
0      0  Disco Elysium: The Final Cut   
1      1                   Half-Life 2   
2      2            Grand Theft Auto V   
3      3                The Orange Box   
4      4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score                                            Summary  
0         97        8.2  Disco Elysium: The Final Cut Disco Elysium Fin...  
1         96        9.2  Half-Life 2 Metacritics 2004 PC Game Year taki...  
2         96        7.8  Grand Theft Auto V Los Santos sprawling sunsoa...  
3         96        9.3  The Orange Box Games included Orange Box compi...  
4         96        9.1  Half-Life HalfLife combine great storytelling ...

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer().fit_transform(complete_data['Summary'])

In [47]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(cv)

In [48]:
print(cs)

[[1.         0.06578947 0.0522887  ... 0.04941327 0.06882472 0.04480108]
 [0.06578947 1.         0.03921652 ... 0.04117772 0.0841191  0.04480108]
 [0.0522887  0.03921652 1.         ... 0.03272757 0.03038949 0.05934561]
 ...
 [0.04941327 0.04117772 0.03272757 ... 1.         0.05265026 0.0467351 ]
 [0.06882472 0.0841191  0.03038949 ... 0.05265026 1.         0.06943409]
 [0.04480108 0.04480108 0.05934561 ... 0.0467351  0.06943409 1.        ]]


In [49]:
cs.shape

(4468, 4468)

In [50]:
Title = "Grand Theft Auto V"
Title

'Grand Theft Auto V'

In [51]:
def recommend_game(game_name):
    id = complete_data[complete_data.Title == game_name].index[0]
    scores = list(enumerate(cs[id]))
    sorted_scores = sorted(scores, key = lambda x:x[1], reverse=True)[1:16]

    for item in sorted_scores:
        print(complete_data.iloc[item[0]].Title)

In [56]:
recommend_game('FIFA 2001 Major League Soccer')

FIFA Soccer 11
FIFA 17
FIFA Soccer 2002
FIFA Soccer 08
FIFA Manager 09
FIFA Soccer 12
FIFA Soccer 2005
FIFA Soccer 10
FIFA Soccer 09
FIFA World Cup: Germany 2006
FIFA Manager 11
FIFA 21
FIFA 07 Soccer
FIFA 16
NHL 2001


In [57]:
import pickle

In [58]:
pickle.dump(complete_data.to_dict(),open('PC_Games.pkl','wb'))

In [59]:
pickle.dump(cs,open('cs.pkl','wb'))