In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from nltk.corpus import stopwords
sw = set(stopwords.words('english'))

from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [2]:
df = pd.read_csv('PC_Games_2021.csv')

In [3]:
df.head()

Unnamed: 0                         Title  \
0           0  Disco Elysium: The Final Cut   
1           1                   Half-Life 2   
2           2            Grand Theft Auto V   
3           3                The Orange Box   
4           4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0    4500 non-null   int64 
 1   Title         4500 non-null   object
 2   Description   4468 non-null   object
 3   Release Date  4500 non-null   object
 4   Metascore     4500 non-null   int64 
 5   User Score    4500 non-null   object
dtypes: int64(2), object(4)
memory usage: 211.1+ KB


In [5]:
df.reset_index(inplace=True)

In [6]:
df.head()

index  Unnamed: 0                         Title  \
0      0           0  Disco Elysium: The Final Cut   
1      1           1                   Half-Life 2   
2      2           2            Grand Theft Auto V   
3      3           3                The Orange Box   
4      4           4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [7]:
df.drop(columns=['index','Unnamed: 0'],inplace=True)

In [8]:
df.head()

Title  \
0  Disco Elysium: The Final Cut   
1                   Half-Life 2   
2            Grand Theft Auto V   
3                The Orange Box   
4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score  
0         97        8.2  
1         96        9.2  
2         96        7.8  
3         96        9.3  
4         96        9.1

In [9]:
df.dropna(inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4468 entries, 0 to 4499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Title         4468 non-null   object
 1   Description   4468 non-null   object
 2   Release Date  4468 non-null   object
 3   Metascore     4468 non-null   int64 
 4   User Score    4468 non-null   object
dtypes: int64(1), object(4)
memory usage: 209.4+ KB


In [11]:
df.reset_index(inplace=True)

In [12]:
complete_data = df.copy()
complete_data

index                         Title  \
0         0  Disco Elysium: The Final Cut   
1         1                   Half-Life 2   
2         2            Grand Theft Auto V   
3         3                The Orange Box   
4         4                     Half-Life   
...     ...                           ...   
4463   4495                    Rugby 2004   
4464   4496   Judge Dredd: Dredd VS Death   
4465   4497             Conflict: Vietnam   
4466   4498        Transformers: The Game   
4467   4499                  Alias (2004)   

                                            Description       Release Date  \
0     Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1     [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2     Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3     Games included in The Orange Box compilation: ...   October 10, 2007   
4     Half-Life combines great storytelling in the t...  November 19, 1998   
...                                                 ...                ...   
4463  Choose from 20 international, all Super 12, an...   November 4, 2003   
4464  It is the third decade of the 22nd century. Un...      March 3, 2005   
4465  Conflict: Vietnam follows the progress of four...    October 5, 2004   
4466  Based on the 2007 live-action feature film, Tr...      June 26, 2007   
4467  Alias is a third-person action adventure conta...      June 17, 2004   

      Metascore User Score  
0            97        8.2  
1            96        9.2  
2            96        7.8  
3            96        9.3  
4            96        9.1  
...         ...        ...  
4463         55        5.5  
4464         55        7.1  
4465         55        7.1  
4466         55        5.5  
4467         55        6.9  

[4468 rows x 6 columns]

In [13]:
new_desc = []
for desc in complete_data['Description']:
    update = desc.split()
    update = [ps.stem(word) for word in update if word.lower() not in sw]
    new_desc.append(update)

In [14]:
complete_data['Summary'] = new_desc

In [15]:
complete_data['Summary'] = complete_data['Summary'].str.join(" ")

In [16]:
complete_data['Summary'] = complete_data['Title']+ " " +complete_data['Summary']

In [17]:
complete_data.head()

index                         Title  \
0      0  Disco Elysium: The Final Cut   
1      1                   Half-Life 2   
2      2            Grand Theft Auto V   
3      3                The Orange Box   
4      4                     Half-Life   

                                         Description       Release Date  \
0  Disco Elysium - The Final Cut is the definitiv...     March 30, 2021   
1  [Metacritic's 2004 PC Game of the Year]  By ta...  November 16, 2004   
2  Los Santos: a sprawling sun-soaked metropolis ...     April 13, 2015   
3  Games included in The Orange Box compilation: ...   October 10, 2007   
4  Half-Life combines great storytelling in the t...  November 19, 1998   

   Metascore User Score                                            Summary  
0         97        8.2  Disco Elysium: The Final Cut disco elysium - f...  
1         96        9.2  Half-Life 2 [metacritic' 2004 pc game year] ta...  
2         96        7.8  Grand Theft Auto V lo santos: sprawl sun-soak ...  
3         96        9.3  The Orange Box game includ orang box compilati...  
4         96        9.1  Half-Life half-lif combin great storytel tradi...

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer().fit_transform(complete_data['Summary'])

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(cv)

In [20]:
print(cs)

[[1.         0.07373211 0.05064915 ... 0.04752485 0.05427825 0.05985503]
 [0.07373211 1.         0.03594426 ... 0.04496938 0.09538218 0.02831827]
 [0.05064915 0.03594426 1.         ... 0.03089102 0.03780077 0.05835841]
 ...
 [0.04752485 0.04496938 0.03089102 ... 1.         0.04729203 0.063885  ]
 [0.05427825 0.09538218 0.03780077 ... 0.04729203 1.         0.0625399 ]
 [0.05985503 0.02831827 0.05835841 ... 0.063885   0.0625399  1.        ]]


In [21]:
cs.shape

(4468, 4468)

In [22]:
Title = "Grand Theft Auto V"
Title

'Grand Theft Auto V'

In [23]:
def recommend_game(game_name):
    id = complete_data[complete_data.Title == game_name].index[0]
    scores = list(enumerate(cs[id]))
    sorted_scores = sorted(scores, key = lambda x:x[1], reverse=True)[1:16]

    for item in sorted_scores:
        print(complete_data.iloc[item[0]].Title)

In [24]:
recommend_game('Grand Theft Auto V')

Sea of Thieves
Feist
Green Hell
Neo Cab
The Survivalists
The Partners
Space Rangers 2: Rise of the Dominators
Unrest
Hitman: Codename 47
Deus Ex: Invisible War
Life is Strange
And Yet It Moves
State of Decay
Devastation
Deadlight


In [25]:
import pickle

In [26]:
pickle.dump(complete_data.to_dict(),open('PC_Games.pkl','wb'))

In [27]:
pickle.dump(cs,open('cs.pkl','wb'))